version: "3.7"

services:
  crafty:
    container_name: crafty
    image: registry.gitlab.com/crafty-controller/crafty-4:4.11.0
    restart: on-failure
    init: true
    environment:
      TZ: Europe/Stockholm
    ports:
      - "18444:8443"
      - "18124:8123"
      - "5520-5550:5520-5550/udp"
      - "19132:19132/udp"
      - "25500-25600:25500-25600"
    volumes:
      - ${APP_DATA_DIR}/data/backups:/crafty/backups
      - ${APP_DATA_DIR}/data/logs:/crafty/logs
      - ${APP_DATA_DIR}/data/servers:/crafty/servers
      - ${APP_DATA_DIR}/data/config:/crafty/app/config
      - ${APP_DATA_DIR}/data/import:/crafty/import